speech_concat_metric:
  class_path: speechcomet.models.SpeechRegressionConcat
  init_args:
    nr_frozen_epochs: 0.3
    keep_trg_embeddings_frozen: True
    keep_src_embeddings_frozen: False
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 0.95
    encoder_model: XLM-RoBERTa
    encoder_model_audio: sonar_speech_encoder_eng
    sonar_ft_freeze_layers: 4
    max_audio_duration: 20.0
    input_modality: audiotext
    fuse_emb_strategy: sum
    pretrained_model: microsoft/infoxlm-large
    pool: avg
    layer: mix
    layer_transformation: sparsemax
    layer_norm: False
    hidden_sizes:
      - 3072
      - 1024
    dropout: 0.1
    batch_size: 4
    train_data: 
      - maikezu/iwslt2026-metrics-shared-train-dev
    validation_data:
      - maikezu/iwslt2026-metrics-shared-train-dev

      
      
trainer: ../../trainer_orkney_accum4.yaml
early_stopping: ../../early_stopping.yaml
model_checkpoint: ../../model_checkpoint.yaml